# Generated by Django 6.0.1 on 2026-01-10 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Логин')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('fullname', models.CharField(max_length=255, verbose_name='ФИО участника')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('district', models.CharField(max_length=100, verbose_name='Район')),
                ('school', models.CharField(max_length=255, verbose_name='Школа')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], verbose_name='Класс')),
                ('teacher_fullname', models.CharField(max_length=255, verbose_name='ФИО учителя')),
                ('is_checked_in', models.BooleanField(default=False, verbose_name='Присутствовал')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['-created_at'],
            },
        ),
    ]
