# Generated by Django 5.2.3 on 2026-01-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Балл'),
        ),
    ]
