# Generated by Django 5.2.3 on 2026-01-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_participant_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер телефона'),
        ),
    ]
