# Generated by Django 6.0.1 on 2026-01-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_alter_participant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='region',
            field=models.CharField(default='', max_length=100, verbose_name='Регион'),
        ),
    ]
