# Generated by Django 6.0.1 on 2026-01-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_participant_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='test_language',
            field=models.CharField(choices=[('ru', 'Русский'), ('uz', "O'zbek")], default='ru', max_length=2, verbose_name='Язык теста'),
        ),
    ]
