# Generated by Django 6.0.1 on 2026-01-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_participant_test_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='telegram_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписан на канал'),
        ),
        migrations.AddField(
            model_name='participant',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
