# Generated by Django 6.0.1 on 2026-01-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_telegram_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('code', models.CharField(max_length=6, verbose_name='Код подтверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждён')),
            ],
            options={
                'verbose_name': 'Подтверждение телефона',
                'verbose_name_plural': 'Подтверждения телефонов',
                'ordering': ['-created_at'],
            },
        ),
    ]
