# Generated by Django 6.0.1 on 2026-01-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_phone_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympiadSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='BOND Olimpiadasi', max_length=255, verbose_name='Название мероприятия')),
                ('event_date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('location', models.CharField(max_length=500, verbose_name='Место проведения')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки олимпиады',
                'verbose_name_plural': 'Настройки олимпиады',
                'ordering': ['-created_at'],
            },
        ),
    ]
