# Generated by Django 6.0.1 on 2026-01-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_olympiadsettings_ticket_price_participant_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payme_cancel_reason',
            field=models.IntegerField(blank=True, null=True, verbose_name='Payme cancel reason'),
        ),
        migrations.AddField(
            model_name='order',
            name='payme_cancel_time',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Payme cancel_time (ms)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payme_create_time',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Payme create_time (ms)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payme_perform_time',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Payme perform_time (ms)'),
        ),
        migrations.AddField(
            model_name='order',
            name='payme_state',
            field=models.IntegerField(blank=True, null=True, verbose_name='Payme state'),
        ),
    ]
