# Generated by Django 6.0.1 on 2026-02-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_order_payme_cancel_reason_order_payme_cancel_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='click_prepare_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Click Prepare ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='click_trans_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Click Transaction ID'),
        ),
    ]
