# Generated by Django 6.0.1 on 2026-02-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_order_click_prepare_id_order_click_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='grade',
            field=models.SmallIntegerField(choices=[(0, "Bog'cha"), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], verbose_name='Класс'),
        ),
    ]
