# Generated by Django 6.0.1 on 2026-02-14 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_order_click_prepare_id_order_click_trans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='public.olympiadsettings', verbose_name='Олимпиада'),
        ),
    ]
