# Generated by Django 6.0.1 on 2026-02-14 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_alter_participant_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='public.olympiadsettings', verbose_name='Олимпиада'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], verbose_name='Класс'),
        ),
    ]
