# Generated by Django 6.0.1 on 2026-02-16 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_remove_olympiadsettings_ticket_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='public.subject', verbose_name='Предмет'),
        ),
    ]
