# Generated by Django 6.0.1 on 2026-02-16 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_order_olympiad_alter_participant_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiadsettings',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='subject',
        ),
        migrations.AddField(
            model_name='order',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='public.subject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='subject',
            name='olympiad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='public.olympiadsettings', verbose_name='Олимпиада'),
        ),
        migrations.AddField(
            model_name='subject',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость билета (сум)'),
        ),
    ]
