# Generated by Django 6.0.1 on 2026-02-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_add_subject_to_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='subject',
        ),
    ]
