# Generated by Django 6.0.1 on 2026-02-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_remove_olympiadsettings_ticket_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiadsettings',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='olympiads/', verbose_name='Иллюстрация'),
        ),
    ]
