# Generated by Django 6.0.1 on 2026-02-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0015_olympiadsettings_illustration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок')),
                ('date_text', models.CharField(blank=True, max_length=100, verbose_name='Текст даты (напр. ОКТЯБРЬ 2024)')),
                ('image', models.ImageField(upload_to='achievements/', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка (необязательно)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Достижение (Зал славы)',
                'verbose_name_plural': 'Достижения (Зал славы)',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
