# Generated by Django 6.0.1 on 2026-02-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0016_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='guides/videos/', verbose_name='Видео файл')),
                ('video_url', models.URLField(blank=True, help_text='Если загружен файл, это поле игнорируется', verbose_name='Ссылка на видео (YouTube/Vimeo)')),
                ('thumbnail', models.ImageField(upload_to='guides/thumbnails/', verbose_name='Превью (обложка)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Видео руководство',
                'verbose_name_plural': 'Видео руководства',
                'ordering': ['-created_at'],
            },
        ),
    ]
