# Generated by Django 6.0.1 on 2026-02-24 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0019_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (подробное)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Длительность (напр. 6 oy)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='Метка (напр. web3h)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='status_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Статус (напр. Yakunlangan)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='team_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Команда (напр. 8 kishi)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='technologies',
            field=models.CharField(blank=True, help_text='Напр: Python, Next JS, React JS, Flutter', max_length=500, verbose_name='Технологии (через запятую)'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='year',
            field=models.CharField(blank=True, max_length=20, verbose_name='Год (напр. 2025)'),
        ),
        migrations.CreateModel(
            name='AchievementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='achievements/gallery/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='public.achievement', verbose_name='Достижение')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Фото галереи',
                'ordering': ['order'],
            },
        ),
    ]
