# Generated by Django 6.0.1 on 2026-02-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0020_achievement_description_achievement_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='label',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='status_text',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='team_size',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='year',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Katnashuvchilar soni'),
        ),
    ]
